//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Home_FA_Kit.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Home_FA_Kit.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить лекарство.
        /// </summary>
        internal static string AddMedicine {
            get {
                return ResourceManager.GetString("AddMedicine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить.
        /// </summary>
        internal static string Button_Add {
            get {
                return ResourceManager.GetString("Button_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создать новое лекарство.
        /// </summary>
        internal static string Button_CreateNewMedicine {
            get {
                return ResourceManager.GetString("Button_CreateNewMedicine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создать новую аптечку.
        /// </summary>
        internal static string Button_CreateNewPharmacy {
            get {
                return ResourceManager.GetString("Button_CreateNewPharmacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сброс.
        /// </summary>
        internal static string Button_ResetFilter {
            get {
                return ResourceManager.GetString("Button_ResetFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить.
        /// </summary>
        internal static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить настройки.
        /// </summary>
        internal static string Button_SaveSettings {
            get {
                return ResourceManager.GetString("Button_SaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сортировать.
        /// </summary>
        internal static string Button_Sort {
            get {
                return ResourceManager.GetString("Button_Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ↑↓.
        /// </summary>
        internal static string Button_SortDirection {
            get {
                return ResourceManager.GetString("Button_SortDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Стоимость: .
        /// </summary>
        internal static string Cost {
            get {
                return ResourceManager.GetString("Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Корректировка препарата.
        /// </summary>
        internal static string EditMedicine {
            get {
                return ResourceManager.GetString("EditMedicine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите активный ингредиент.
        /// </summary>
        internal static string Entry_MedicineActiveIngredient {
            get {
                return ResourceManager.GetString("Entry_MedicineActiveIngredient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите стоимость.
        /// </summary>
        internal static string Entry_MedicineCost {
            get {
                return ResourceManager.GetString("Entry_MedicineCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите страну.
        /// </summary>
        internal static string Entry_MedicineCountry {
            get {
                return ResourceManager.GetString("Entry_MedicineCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите описание.
        /// </summary>
        internal static string Entry_MedicineDescription {
            get {
                return ResourceManager.GetString("Entry_MedicineDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите срок годности (dd.MM.yyyy).
        /// </summary>
        internal static string Entry_MedicineExpirationDate {
            get {
                return ResourceManager.GetString("Entry_MedicineExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите форму.
        /// </summary>
        internal static string Entry_MedicineForm {
            get {
                return ResourceManager.GetString("Entry_MedicineForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите производителя.
        /// </summary>
        internal static string Entry_MedicineManufacturer {
            get {
                return ResourceManager.GetString("Entry_MedicineManufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите название лекарства.
        /// </summary>
        internal static string Entry_MedicineName {
            get {
                return ResourceManager.GetString("Entry_MedicineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Примечание.
        /// </summary>
        internal static string Entry_MedicineNote {
            get {
                return ResourceManager.GetString("Entry_MedicineNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите фармакологическое действие.
        /// </summary>
        internal static string Entry_MedicinePharmacologicalEffect {
            get {
                return ResourceManager.GetString("Entry_MedicinePharmacologicalEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите количество.
        /// </summary>
        internal static string Entry_MedicineQuantity {
            get {
                return ResourceManager.GetString("Entry_MedicineQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите название аптечки.
        /// </summary>
        internal static string Entry_PharmacyName {
            get {
                return ResourceManager.GetString("Entry_PharmacyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Срок годности: .
        /// </summary>
        internal static string ExpirationDate {
            get {
                return ResourceManager.GetString("ExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Просрочено.
        /// </summary>
        internal static string Expired {
            get {
                return ResourceManager.GetString("Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Просроченные лекарства.
        /// </summary>
        internal static string ExpiredMedicines {
            get {
                return ResourceManager.GetString("ExpiredMedicines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ввод нового лекарства.
        /// </summary>
        internal static string Label_CreateNewMedicine {
            get {
                return ResourceManager.GetString("Label_CreateNewMedicine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создание новой аптечки.
        /// </summary>
        internal static string Label_CreateNewPharmacy {
            get {
                return ResourceManager.GetString("Label_CreateNewPharmacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактирование аптечки.
        /// </summary>
        internal static string Label_EditPharmacy {
            get {
                return ResourceManager.GetString("Label_EditPharmacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Лекарства.
        /// </summary>
        internal static string Label_Medicines {
            get {
                return ResourceManager.GetString("Label_Medicines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статистика по аптечкам.
        /// </summary>
        internal static string Label_PharmacyStatistics {
            get {
                return ResourceManager.GetString("Label_PharmacyStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите дату.
        /// </summary>
        internal static string Label_SelectDate {
            get {
                return ResourceManager.GetString("Label_SelectDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите начальную дату.
        /// </summary>
        internal static string Label_SelectDateFrom {
            get {
                return ResourceManager.GetString("Label_SelectDateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите конечную дату (если нужно).
        /// </summary>
        internal static string Label_SelectDateTo {
            get {
                return ResourceManager.GetString("Label_SelectDateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите дни недели.
        /// </summary>
        internal static string Label_SelectDaysOfWeek {
            get {
                return ResourceManager.GetString("Label_SelectDaysOfWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите язык.
        /// </summary>
        internal static string Label_SelectLanguage {
            get {
                return ResourceManager.GetString("Label_SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите лекарство.
        /// </summary>
        internal static string Label_SelectMedicine {
            get {
                return ResourceManager.GetString("Label_SelectMedicine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите тему.
        /// </summary>
        internal static string Label_SelectTheme {
            get {
                return ResourceManager.GetString("Label_SelectTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите время суток.
        /// </summary>
        internal static string Label_SelectTime {
            get {
                return ResourceManager.GetString("Label_SelectTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Приём лекарств.
        /// </summary>
        internal static string Medication {
            get {
                return ResourceManager.GetString("Medication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Аптечки.
        /// </summary>
        internal static string Pharmacies {
            get {
                return ResourceManager.GetString("Pharmacies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите категорию.
        /// </summary>
        internal static string Picker_Category {
            get {
                return ResourceManager.GetString("Picker_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите подкатегорию.
        /// </summary>
        internal static string Picker_SubCategory {
            get {
                return ResourceManager.GetString("Picker_SubCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество: .
        /// </summary>
        internal static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поиск.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статистика.
        /// </summary>
        internal static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
    }
}
